<?php
declare(strict_types = 1);

use NatOkpe\Wp\Plugin\NexusdreamSetup\Engine;

/* Config: Post types */
return [
    'job_position' => [
        'label'  => 'Position',
        'labels' => [
            'name'                     => 'Positions',
            'singular_name'            => 'Position',
            'add_new'                  => 'Add New Position',
            'add_new_item'             => 'Add New Position',
            'edit_item'                => 'Edit Position',
            'new_item'                 => 'New Position',
            'view_item'                => 'View Position',
            'view_items'               => 'View Positions',
            'search_items'             => 'Search Positions',
            'not_found'                => 'No positions found',
            'not_found_in_trash'       => 'No positions found in Trash',
            'parent_item_colon'        => 'Parent Position:',
            'all_items'                => 'All Positions',
            'archives'                 => 'Position Archives',
            'attributes'               => 'Position Attributes',
            'insert_into_item'         => 'Insert into position',
            'uploaded_to_this_item'    => 'Uploaded to this position',
            'featured_image'           => 'Featured image',
            'set_featured_image'       => 'Set featured image',
            'remove_featured_image'    => 'Remove featured image',
            'use_featured_image'       => 'Use as featured image',
            'menu_name'                => 'Positions',
            'filter_items_list'        => 'Filter positions list',
            'filter_by_date'           => 'Filter by date',
            'items_list_navigation'    => 'Positions list navigation',
            'items_list'               => 'Positions list',
            'item_published'           => 'Position published.',
            'item_published_privately' => 'Position published privately.',
            'item_reverted_to_draft'   => 'Position reverted to draft.',
            'item_trashed'             => 'Position trashed.',
            'item_scheduled'           => 'Position scheduled.',
            'item_updated'             => 'Position updated.',
            'item_link'                => 'Position Link',
            'item_link_description'    => 'A link to a position.',
        ],
        'description'         => 'Positions',
        'public'              => true,
        'hierarchical'        => false,
        'exclude_from_search' => false,
        'publicly_queryable'  => true,
        'show_ui'             => true,
        'show_in_menu'        => true,
        'show_in_nav_menus'   => true,
        'show_in_admin_bar'   => true,
        'show_in_rest'        => true,
        'menu_position'       => 20,
        'menu_icon'        => 'dashicons-filter',
        'capability_type'     => ['position', 'positions'],
        // 'capabilities'     => [],
        'map_meta_cap'        => true,
        'supports'            => [
            'title',
            // 'editor',
            // 'trackbacks',
            // 'author',
            'excerpt',
            'page-attributes',
            // 'thumbnail',
        ],
        'taxonomies' => [
        ],
        'has_archive' => false,
        'rewrite' => [
        //     'slug' => '',
            'with_front' => false,
        ],
        // 'query_var ' => '',
        'can_export'       => true,
        'delete_with_user' => false,
    ],

    // Register the "application" custom post type
    'job_application' => [
        'label'  => 'Application',
        'labels' => [
            'name'                     => 'Applications',
            'singular_name'            => 'Application',
            'add_new'                  => 'Add New Application',
            'add_new_item'             => 'Add New Application',
            'edit_item'                => 'Edit Application',
            'new_item'                 => 'New Application',
            'view_item'                => 'View Application',
            'view_items'               => 'View Applications',
            'search_items'             => 'Search Applications',
            'not_found'                => 'No applications found',
            'not_found_in_trash'       => 'No applications found in Trash',
            'parent_item_colon'        => 'Parent Application:',
            'all_items'                => 'All Applications',
            'archives'                 => 'Application Archives',
            'attributes'               => 'Application Attributes',
            'insert_into_item'         => 'Insert into application',
            'uploaded_to_this_item'    => 'Uploaded to this application',
            'featured_image'           => 'Featured image',
            'set_featured_image'       => 'Set featured image',
            'remove_featured_image'    => 'Remove featured image',
            'use_featured_image'       => 'Use as featured image',
            'menu_name'                => 'Applications',
            'filter_items_list'        => 'Filter applications list',
            'filter_by_date'           => 'Filter by date',
            'items_list_navigation'    => 'Applications list navigation',
            'items_list'               => 'Applications list',
            'item_published'           => 'Application published.',
            'item_published_privately' => 'Application published privately.',
            'item_reverted_to_draft'   => 'Application reverted to draft.',
            'item_trashed'             => 'Application trashed.',
            'item_scheduled'           => 'Application scheduled.',
            'item_updated'             => 'Application updated.',
            'item_link'                => 'Application Link',
            'item_link_description'    => 'A link to a application.',
        ],
        'description'         => 'Applications',
        'public'              => false,
        'hierarchical'        => false,
        'exclude_from_search' => true,
        'publicly_queryable'  => false,
        'show_ui'             => true,
        'show_in_menu'        => true,
        'show_in_nav_menus'   => true,
        'show_in_admin_bar'   => true,
        'show_in_rest'        => true,
        'menu_position'       => 20,
        'menu_icon'           => 'dashicons-id',
        'capability_type'     => ['application', 'applications'],
        // 'capabilities'     => [],
        'map_meta_cap'        => true,
        'supports'            => [
            'title',
            // 'editor',
            // 'trackbacks',
            // 'author',
            // 'excerpt',
            'page-attributes',
            // 'thumbnail',
        ],
        'taxonomies' => [
        ],
        'has_archive' => false,
        'rewrite' => [
        //     'slug' => '',
            'with_front' => false,
        ],
        // 'query_var ' => '',
        'can_export'       => true,
        'delete_with_user' => false,
    ],

    'faq' => [
        'label'  => 'FAQs',
        'labels' => [
            'name'                     => 'FAQs',
            'singular_name'            => 'FAQ',
            'add_new'                  => 'Add New FAQ',
            'add_new_item'             => 'Add New FAQ',
            'edit_item'                => 'Edit FAQ',
            'new_item'                 => 'New FAQ',
            'view_item'                => 'View FAQ',
            'view_items'               => 'View FAQs',
            'search_items'             => 'Search FAQs',
            'not_found'                => 'No faqs found',
            'not_found_in_trash'       => 'No faqs found in Trash',
            'parent_item_colon'        => 'Parent FAQ:',
            'all_items'                => 'All FAQs',
            'archives'                 => 'FAQ Archives',
            'attributes'               => 'FAQ Attributes',
            'insert_into_item'         => 'Insert into faq',
            'uploaded_to_this_item'    => 'Uploaded to this faq',
            'featured_image'           => 'Featured image',
            'set_featured_image'       => 'Set featured image',
            'remove_featured_image'    => 'Remove featured image',
            'use_featured_image'       => 'Use as featured image',
            'menu_name'                => 'FAQs',
            'filter_items_list'        => 'Filter faqs list',
            'filter_by_date'           => 'Filter by date',
            'items_list_navigation'    => 'FAQs list navigation',
            'items_list'               => 'FAQs list',
            'item_published'           => 'FAQ published.',
            'item_published_privately' => 'FAQ published privately.',
            'item_reverted_to_draft'   => 'FAQ reverted to draft.',
            'item_trashed'             => 'FAQ trashed.',
            'item_scheduled'           => 'FAQ scheduled.',
            'item_updated'             => 'FAQ updated.',
            'item_link'                => 'FAQ Link',
            'item_link_description'    => 'A link to a faq.',
        ],
        'description'         => 'Frequently Asked Questions (FAQs)',
        'public'              => true,
        'hierarchical'        => false,
        'exclude_from_search' => false,
        'publicly_queryable'  => true,
        'show_ui'             => true,
        'show_in_menu'        => true,
        'show_in_nav_menus'   => true,
        'show_in_admin_bar'   => true,
        'show_in_rest'        => true,
        'menu_position'       => 20,
        'menu_icon'        => 'dashicons-editor-help',
        'capability_type'     => ['faq', 'faqs'],
        // 'capabilities'     => [],
        'map_meta_cap'        => true,
        'supports'            => [
            'title',
            'editor',
            'trackbacks',
            'author',
            'excerpt',
            'page-attributes',
            'thumbnail',
        ],
        'taxonomies' => [
            'faq-topic'
        ],
        'has_archive' => false,
        'rewrite' => [
        //     'slug' => '',
            'with_front' => false,
        ],
        // 'query_var'        => '',
        'can_export'       => true,
        'delete_with_user' => false,
    ],
];
